<?php
    /****************************************************
     * Generated by YaPiG Installation. Do not modify   *
     ****************************************************/

    /**
     * Secure dir
     *
     * This directory will store all dynamic information.
     *
     *
     */

     $SECURE_DIR= $BASE_DIR . "yapig_data.1c06231e4395900404818705c1e5f502/";
    /**
     * gid-directory correspondence file.
     *
     * This file will store the correspondence between gid and dirs in
     * the common correspondence file format.Sample line:
     *    gid $EQUAL value
     */

    $GID_DIRS= $SECURE_DIR . 'gid-dirs.043a0052c644ccc0f8d83a2ab0580890';

    /** phid->filename Correspondence file.
     *
     * This file will have the correspondece beteen photo identificator phid
     * and image filename (just filename without path information).
     *
     * Will be stored in the common correspondence file format. Sample line:
     * phid => phid_filename.ext
     *
     */

    $PHID_FILENAMES='phid.043a0052c644ccc0f8d83a2ab0580890';

    /**
     * GD_VERSION
     * When yapig is installed it is detected which version is in this system.
     * If it is not automatically detected modify this field. 
     * Set =1 for using 1.x GD library
     * Set =2 for using 2.x GD library
     * 
     */
     $GD_VERSION=2;


?>